//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLINHANVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string maNhanVien { get; set; }
        public string tenNhanVien { get; set; }
        public string ngaysinh { get; set; }
        public int luong { get; set; }
        public string hinhanh { get; set; }
        public string maphong { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
    }
}
